/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as SugerenciasRouteImport } from './routes/sugerencias'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InstalacionRouteImport } from './routes/instalacion'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as DescargarRouteImport } from './routes/descargar'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as ActualizacionesRouteImport } from './routes/actualizaciones'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicVoiceTranscribeRouteImport } from './routes/api/public/voice-transcribe'
import { Route as ApiPublicVoiceStructureRouteImport } from './routes/api/public/voice-structure'
import { Route as ApiPublicPlantillasBaseRouteImport } from './routes/api.public.plantillas-base'
import { Route as ApiPublicPacSearchRouteImport } from './routes/api/public/pac-search'
import { Route as ApiPublicAsistenteRayenZipRouteImport } from './routes/api.public.asistente-rayen-zip'

const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const SugerenciasRoute = SugerenciasRouteImport.update({
  id: '/sugerencias',
  path: '/sugerencias',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InstalacionRoute = InstalacionRouteImport.update({
  id: '/instalacion',
  path: '/instalacion',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const DescargarRoute = DescargarRouteImport.update({
  id: '/descargar',
  path: '/descargar',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualizacionesRoute = ActualizacionesRouteImport.update({
  id: '/actualizaciones',
  path: '/actualizaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVoiceTranscribeRoute =
  ApiPublicVoiceTranscribeRouteImport.update({
    id: '/api/public/voice-transcribe',
    path: '/api/public/voice-transcribe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicVoiceStructureRoute = ApiPublicVoiceStructureRouteImport.update({
  id: '/api/public/voice-structure',
  path: '/api/public/voice-structure',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlantillasBaseRoute = ApiPublicPlantillasBaseRouteImport.update({
  id: '/api/public/plantillas-base',
  path: '/api/public/plantillas-base',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPacSearchRoute = ApiPublicPacSearchRouteImport.update({
  id: '/api/public/pac-search',
  path: '/api/public/pac-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAsistenteRayenZipRoute =
  ApiPublicAsistenteRayenZipRouteImport.update({
    id: '/api/public/asistente-rayen-zip',
    path: '/api/public/asistente-rayen-zip',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actualizaciones': typeof ActualizacionesRoute
  '/biblioteca': typeof BibliotecaRoute
  '/changelog': typeof ChangelogRoute
  '/dashboard': typeof DashboardRoute
  '/descargar': typeof DescargarRoute
  '/editor': typeof EditorRoute
  '/instalacion': typeof InstalacionRoute
  '/login': typeof LoginRoute
  '/privacidad': typeof PrivacidadRoute
  '/roadmap': typeof RoadmapRoute
  '/sugerencias': typeof SugerenciasRoute
  '/terminos': typeof TerminosRoute
  '/api/public/asistente-rayen-zip': typeof ApiPublicAsistenteRayenZipRoute
  '/api/public/pac-search': typeof ApiPublicPacSearchRoute
  '/api/public/plantillas-base': typeof ApiPublicPlantillasBaseRoute
  '/api/public/voice-structure': typeof ApiPublicVoiceStructureRoute
  '/api/public/voice-transcribe': typeof ApiPublicVoiceTranscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actualizaciones': typeof ActualizacionesRoute
  '/biblioteca': typeof BibliotecaRoute
  '/changelog': typeof ChangelogRoute
  '/dashboard': typeof DashboardRoute
  '/descargar': typeof DescargarRoute
  '/editor': typeof EditorRoute
  '/instalacion': typeof InstalacionRoute
  '/login': typeof LoginRoute
  '/privacidad': typeof PrivacidadRoute
  '/roadmap': typeof RoadmapRoute
  '/sugerencias': typeof SugerenciasRoute
  '/terminos': typeof TerminosRoute
  '/api/public/asistente-rayen-zip': typeof ApiPublicAsistenteRayenZipRoute
  '/api/public/pac-search': typeof ApiPublicPacSearchRoute
  '/api/public/plantillas-base': typeof ApiPublicPlantillasBaseRoute
  '/api/public/voice-structure': typeof ApiPublicVoiceStructureRoute
  '/api/public/voice-transcribe': typeof ApiPublicVoiceTranscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actualizaciones': typeof ActualizacionesRoute
  '/biblioteca': typeof BibliotecaRoute
  '/changelog': typeof ChangelogRoute
  '/dashboard': typeof DashboardRoute
  '/descargar': typeof DescargarRoute
  '/editor': typeof EditorRoute
  '/instalacion': typeof InstalacionRoute
  '/login': typeof LoginRoute
  '/privacidad': typeof PrivacidadRoute
  '/roadmap': typeof RoadmapRoute
  '/sugerencias': typeof SugerenciasRoute
  '/terminos': typeof TerminosRoute
  '/api/public/asistente-rayen-zip': typeof ApiPublicAsistenteRayenZipRoute
  '/api/public/pac-search': typeof ApiPublicPacSearchRoute
  '/api/public/plantillas-base': typeof ApiPublicPlantillasBaseRoute
  '/api/public/voice-structure': typeof ApiPublicVoiceStructureRoute
  '/api/public/voice-transcribe': typeof ApiPublicVoiceTranscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actualizaciones'
    | '/biblioteca'
    | '/changelog'
    | '/dashboard'
    | '/descargar'
    | '/editor'
    | '/instalacion'
    | '/login'
    | '/privacidad'
    | '/roadmap'
    | '/sugerencias'
    | '/terminos'
    | '/api/public/asistente-rayen-zip'
    | '/api/public/pac-search'
    | '/api/public/plantillas-base'
    | '/api/public/voice-structure'
    | '/api/public/voice-transcribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actualizaciones'
    | '/biblioteca'
    | '/changelog'
    | '/dashboard'
    | '/descargar'
    | '/editor'
    | '/instalacion'
    | '/login'
    | '/privacidad'
    | '/roadmap'
    | '/sugerencias'
    | '/terminos'
    | '/api/public/asistente-rayen-zip'
    | '/api/public/pac-search'
    | '/api/public/plantillas-base'
    | '/api/public/voice-structure'
    | '/api/public/voice-transcribe'
  id:
    | '__root__'
    | '/'
    | '/actualizaciones'
    | '/biblioteca'
    | '/changelog'
    | '/dashboard'
    | '/descargar'
    | '/editor'
    | '/instalacion'
    | '/login'
    | '/privacidad'
    | '/roadmap'
    | '/sugerencias'
    | '/terminos'
    | '/api/public/asistente-rayen-zip'
    | '/api/public/pac-search'
    | '/api/public/plantillas-base'
    | '/api/public/voice-structure'
    | '/api/public/voice-transcribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActualizacionesRoute: typeof ActualizacionesRoute
  BibliotecaRoute: typeof BibliotecaRoute
  ChangelogRoute: typeof ChangelogRoute
  DashboardRoute: typeof DashboardRoute
  DescargarRoute: typeof DescargarRoute
  EditorRoute: typeof EditorRoute
  InstalacionRoute: typeof InstalacionRoute
  LoginRoute: typeof LoginRoute
  PrivacidadRoute: typeof PrivacidadRoute
  RoadmapRoute: typeof RoadmapRoute
  SugerenciasRoute: typeof SugerenciasRoute
  TerminosRoute: typeof TerminosRoute
  ApiPublicAsistenteRayenZipRoute: typeof ApiPublicAsistenteRayenZipRoute
  ApiPublicPacSearchRoute: typeof ApiPublicPacSearchRoute
  ApiPublicPlantillasBaseRoute: typeof ApiPublicPlantillasBaseRoute
  ApiPublicVoiceStructureRoute: typeof ApiPublicVoiceStructureRoute
  ApiPublicVoiceTranscribeRoute: typeof ApiPublicVoiceTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sugerencias': {
      id: '/sugerencias'
      path: '/sugerencias'
      fullPath: '/sugerencias'
      preLoaderRoute: typeof SugerenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instalacion': {
      id: '/instalacion'
      path: '/instalacion'
      fullPath: '/instalacion'
      preLoaderRoute: typeof InstalacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/descargar': {
      id: '/descargar'
      path: '/descargar'
      fullPath: '/descargar'
      preLoaderRoute: typeof DescargarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualizaciones': {
      id: '/actualizaciones'
      path: '/actualizaciones'
      fullPath: '/actualizaciones'
      preLoaderRoute: typeof ActualizacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/voice-transcribe': {
      id: '/api/public/voice-transcribe'
      path: '/api/public/voice-transcribe'
      fullPath: '/api/public/voice-transcribe'
      preLoaderRoute: typeof ApiPublicVoiceTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/voice-structure': {
      id: '/api/public/voice-structure'
      path: '/api/public/voice-structure'
      fullPath: '/api/public/voice-structure'
      preLoaderRoute: typeof ApiPublicVoiceStructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/plantillas-base': {
      id: '/api/public/plantillas-base'
      path: '/api/public/plantillas-base'
      fullPath: '/api/public/plantillas-base'
      preLoaderRoute: typeof ApiPublicPlantillasBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pac-search': {
      id: '/api/public/pac-search'
      path: '/api/public/pac-search'
      fullPath: '/api/public/pac-search'
      preLoaderRoute: typeof ApiPublicPacSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/asistente-rayen-zip': {
      id: '/api/public/asistente-rayen-zip'
      path: '/api/public/asistente-rayen-zip'
      fullPath: '/api/public/asistente-rayen-zip'
      preLoaderRoute: typeof ApiPublicAsistenteRayenZipRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActualizacionesRoute: ActualizacionesRoute,
  BibliotecaRoute: BibliotecaRoute,
  ChangelogRoute: ChangelogRoute,
  DashboardRoute: DashboardRoute,
  DescargarRoute: DescargarRoute,
  EditorRoute: EditorRoute,
  InstalacionRoute: InstalacionRoute,
  LoginRoute: LoginRoute,
  PrivacidadRoute: PrivacidadRoute,
  RoadmapRoute: RoadmapRoute,
  SugerenciasRoute: SugerenciasRoute,
  TerminosRoute: TerminosRoute,
  ApiPublicAsistenteRayenZipRoute: ApiPublicAsistenteRayenZipRoute,
  ApiPublicPacSearchRoute: ApiPublicPacSearchRoute,
  ApiPublicPlantillasBaseRoute: ApiPublicPlantillasBaseRoute,
  ApiPublicVoiceStructureRoute: ApiPublicVoiceStructureRoute,
  ApiPublicVoiceTranscribeRoute: ApiPublicVoiceTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
